### ISSUE TITLE
[Core] Encapsulate various packages throughout CLI/ Break up Do struct

### ISSUE THREAD

**Issue by VoR0220** [monax/cli#1143]
Problem: Currently many of our packages are incredibly overreliant on the *Do struct. I don't think this is good practice. The *Do struct should be our monad and it should fill all needed parts of the tool to execute, but it should not be passed around as it is currently.

Solution: Encapsulate all the various unique portions of CLI into their own parts, and structure them in a way where the Do fills a definition struct needed to complete a task, and then use that struct for the rest of the tasks completion. Finally, make Do immutable. Not only does this make it easier to read the code, it creates a more modular design.

**Comment by silasdavis** [comment]
I tend to agree with this. I have refactored away over-dependence on a single mega-argument being passed through in eris-db. Having a large single-argument struct obscures the true functional dependencies of a function making it harder to reason about and more onerous to debug (more to mock, more to worry about).

However, there is a tradeoff; since go lacks named arguments long positional parameters can be error-prone and similarly obscuring of the functions purpose and dependencies. A good editor or IDE can give parameter name hints (gogland/intellij does this), and when the parameters are reasonably named the intention can be fairly clear.

I think a good middle way is by the following heuristic: if an function has more than about 4-5 arguments consider defining a struct contained for some subset of its arguments. Sometimes even if this is single-use it is still worth doing. Ideally one can find certain 'projections' of the mega-argument that will be useful in multiple contexts and/or have some intrinsic meaning. 

Though I would avoid passing a struct argument with fields that the receiving function will never if I have an existing struct argument that is almost exactly what I need for a new function apart from a single superfluous field then I might be inclined to let that slide for the sake of simplicity, particularly if the existing struct argument has meaning.

If function has a lot of adjacent arguments of the same type then I would almost always use a struct to help avoid positional errors. An exception perhaps being something that I might use `UpdatePixel(x, y)` rather than `UpdatePixel(Point{x: x, y: y})` where there is an established convention and the overhead of struct creation might be significant... But even then... `func Translate(x, y, c int) (x, y int)` ?

**Comment by VoR0220** [comment]
huh? What are you talking about Go lacks named arguments? I think you might be trying to communicate a different concept...because I use named arguments all the time with Go. As for the tradeoff...I don't see it...all of that can be done with a proxy struct that implements all the methods that you might require.

**Comment by VoR0220** [comment]
ah...you mean default arguments...you can replicate this by creating a helper function to set a default parameter.

**Comment by silasdavis** [comment]
Go does not have named arguments for functions, which is what this is about.

**Comment by VoR0220** [comment]
Correct. Go does not have default parameters. However this is fairly easy to overcome imo.

**Comment by zramsay** [comment]
re-named to reflect what we're actually doing. started in #1162 with keys

**Comment by VoR0220** [comment]
...encapsulation is the more common term for this kind of architectural restructuring.

**Comment by zramsay** [comment]
should happen as we work through the cli and fillet the :fish:
