### ISSUE TITLE
[Services] migrate service definition files to docker-compose compatible yamls

### ISSUE THREAD

**Issue by compleatang** [monax/cli#1239]
**Problem** -- currently our service definition files are just close enough to docker-compose yamls to be dangerous. We are out of step with the docker community in this regard. While many have taken docker-compose.yaml's as a leaping off point for more precision in their services (see, [compose2kube](https://github.com/kelseyhightower/compose2kube) which allows Kubernetes to run docker-compose files, [rancher os](https://github.com/rancher/os), and also the [docker cloud spec](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/)), we currently are too far removed to fall into that category. We use toml files instead of yaml's for one. For two, we have a range of custom fields (which is OK), and some fields where the keys to them are not exactly the same as in docker-compose.

This problem, admittedly, does not have a straight forward fix. Docker-compose is written in python so we cannot cleanly extract the library they use to formulate the action struct that will be passed to Docker. There is a [docker supported library in golang](https://github.com/docker/libcompose) which is marked as experimental. That does appear to be used by some high profile go-based systems tho (primarily RancherOS). 

The only reasonable solution I can find would wrap libcompose, map the struct they use to the go-dockerclient ([which they don't use](https://github.com/docker/libcompose/search?q=go-dockerclient&type=Commits&utf8=%E2%9C%93)), or to write our own wrapper to specification. 

Also, I've thought about this for a long time and I'm not sure I 100% see the necessity to be in line with docker-compose files. While it would be very nice to be able to clone a project and `eris services start` it, we've never had this request from existing users. 

Adding an issue because I've been considering costs:benefits, and wanted to open up to users for input, feedback, and/or pull requests ;)

**Comment by marc4gov** [comment]
I can't oversee the technical implementation details you're describing, but I tried working with the current service definition files. If there would be a straightforward way to use toml service files in order to link my custom docker containers, I'm ok. 

Most of the time, I only need to link my front-end, back-end node api and ipfs containers, to have a working app for Eris. So if there would be a standard recipe for that (including container naming, linking, ports etc.), that's fine with me. 
Maybe that's already possible, but haven't been able to use it properly...

**Comment by zramsay** [comment]
no longer part of the direction of the platform
