### ISSUE TITLE
'eris chains make' doesn't create config.toml

### ISSUE THREAD

**Issue by NodeGuy** [monax/cli#1268]
Please include in your bug report:

- [ ] `docker version`

Docker version 17.03.0-ce, build 3a232c8

- [ ] `eris version`

Eris CLI Version: 0.16.0

- [ ] `go version` (if applicable)

go version go1.7.4 linux/amd64

- [ ] operating system details (osx/windows/linux)

Linux

- [ ] what you expected to happen

To be able to make and to start a chain.

- [ ] what actually happened

```
vagrant@contrib-jessie:/vagrant/eris-db.js$ eris chains make test --unsafe
vagrant@contrib-jessie:/vagrant/eris-db.js$ eris chains start test --init-dir ~/.eris/chains/test
Missing config.toml in /home/vagrant/.eris/chains/test. Try [eris chains make] first
vagrant@contrib-jessie:/vagrant/eris-db.js$ ls ~/.eris/chains/test/
accounts.csv  accounts.json  addresses.csv  test_full_000  validators.csv
```

**Comment by benjaminbollen** [comment]
`test_full_000` is the directory that contains the `config.toml`, `genesis.json`, and `priv_validator.json`.  From 0.16 onwards these node-specific files are always written to a directory, where on previous versions of tooling if there was just one node, it would not create subdirrectories.

**Comment by zramsay** [comment]
yeah this was changed in #1096 to simplify both the code and how the tool works for users

**Comment by NodeGuy** [comment]
`eris chains make` advises me:

> The make process will *not* start a chain for you. You will want to use
the [eris chains start NAME --init-dir ~/.eris/chains/NAME] for that
which will import all of the files which make creates into containers and
start your shiny new chain.

This failed so how do you advise me to start the chain?

**Comment by VoR0220** [comment]
@NodeGuy so `eris chains make` doesn't fail or exit with anything bad, correct?

**Comment by zramsay** [comment]
as already specified by @benjaminbollen in his comment above, it is the chain sub-directory that holds the config.toml which should be the directory passed into `--init-dir`. 

I have also previously supplied you with [this gist](https://gist.github.com/zramsay/c03c46fbb88ce2aab201632f84776092#file-eris_do-sh-L39) which specifies _exactly_ how `chains start` should be run (see L39) and you have confirmed that this worked.

Since you have uncovered a documentation issue, please either re-name the issue to reflect this or submit a PR [here](https://github.com/monax/eris/blob/release-0.16/cmd/chains.go#L81). As a member of the platform team you are strongly encouraged to do the latter.

**Comment by NodeGuy** [comment]
@VoR0220 Correct.

@zramsay I tried changing `eris chains start` to match your gist and it failed like this:

```
$ eris chains start test --init-dir ~/.eris/chains/test/test_full_000
Could not import data: getwd: no such file or directory
```

**Comment by zramsay** [comment]
that's coming from https://github.com/monax/eris/blob/release-0.16/chains/chains.go#L434

**Comment by NodeGuy** [comment]
This is working outside of Vagrant.
